"""Compliance module — the editable disclaimer behind every BASIS report.

Single source of truth for the compliance disclaimer text:

  data/disclaimer.txt            the stored text (created on first save; absent = default)
  templates/_disclaimer.html     the report-footer partial every PDF template includes —
                                 REGENERATED from the stored text on every save, never
                                 hand-edited

Consumers:
  * every report template, via {% include "_disclaimer.html" %}
  * report emails, via cot_scheduled_email.DISCLAIMER_TEXT -> get_text()
  * Morning Coffee (OneDrive\\Personal\\AI\\Futures_Movements\\main.py) reads
    data/disclaimer.txt directly at send time, falling back to its own baked-in copy

DEFAULT_TEXT below is the standard XP Investments US, LLC disclaimer (2026-08); the
Revert button on the page restores it.
"""
from __future__ import annotations

import html
import re
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TXT_PATH = ROOT / "data" / "disclaimer.txt"
PARTIAL_PATH = ROOT / "templates" / "_disclaimer.html"

DEFAULT_TEXT = (
    "This material was prepared by XP Investments US, LLC (“XP Investments”), a member of "
    "FINRA, SIPC and NFA. XP Investments and its affiliates, parent, shareholders, directors, "
    "officers, employees, and licensors will not be liable (individually, jointly, or severally) "
    "to you or any other person as a result of your access, reception, or use of the information "
    "contained in this communication. All opinions, projections, and estimates constitute the "
    "judgment of the author as of the date of transmission and these, plus any other information "
    "contained herein, are subject to change without notice. Nothing in this report constitutes a "
    "representation that any investment strategy or recommendation contained herein is suitable "
    "or appropriate to a recipient’s individual circumstances or otherwise constitutes a "
    "personal recommendation. This report is published solely for information purposes, it does "
    "not constitute an advertisement and is not to be construed as a solicitation or an offer to "
    "buy or sell any securities or related financial instruments. This material (including any "
    "attachments) is confidential, may contain proprietary or privileged information and is "
    "intended for the named recipient(s) only."
)


def _normalise(text: str) -> str:
    """Collapse editor line breaks / doubled spaces into one flowing paragraph."""
    return re.sub(r"\s+", " ", (text or "")).strip()


def get_text() -> str:
    """The disclaimer currently in force: the stored edit, else the standard default."""
    try:
        stored = _normalise(TXT_PATH.read_text(encoding="utf-8"))
        if stored:
            return stored
    except OSError:
        pass
    return DEFAULT_TEXT


def is_custom() -> bool:
    return get_text() != DEFAULT_TEXT


def partial_text() -> str:
    """The disclaimer text currently baked into the report partial (drift check)."""
    try:
        m = re.search(r'<div class="fine">\s*(.*?)\s*</div>',
                      PARTIAL_PATH.read_text(encoding="utf-8"), re.S)
        return _normalise(html.unescape(m.group(1))) if m else ""
    except OSError:
        return ""


def _write_partial(text: str) -> None:
    body = textwrap.fill(html.escape(text, quote=False), width=98,
                         initial_indent="  ", subsequent_indent="  ")
    PARTIAL_PATH.write_text(
        '{#- Shared compliance disclaimer, pulled into the foot of every report via\n'
        '    {% include "_disclaimer.html" %}. GENERATED by the Compliance page\n'
        '    (src/compliance.py) from data/disclaimer.txt — edit it THERE, not here. -#}\n'
        '<div class="disclaimer">DISCLAIMER</div>\n'
        '<div class="fine">\n' + body + "\n</div>\n",
        encoding="utf-8")


def save_text(text: str) -> str:
    """Persist an edited disclaimer and regenerate the report partial. Returns the
    normalised text now in force. Raises ValueError on an empty submission."""
    text = _normalise(text)
    if not text:
        raise ValueError("The disclaimer cannot be empty.")
    TXT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TXT_PATH.write_text(text + "\n", encoding="utf-8")
    _write_partial(text)
    return text


def render_page() -> None:
    """The 🛡️ Compliance page (SYSTEM section, admin-only — the caller gates access)."""
    import streamlit as st

    st.subheader("🛡️ Compliance")
    st.caption(
        "House compliance text applied across BASIS output. Edits take effect on the next "
        "report build or scheduled email — nothing already sent changes."
    )

    st.markdown("#### Disclaimer")
    st.caption(
        "Appears at the foot of every report PDF (via `templates/_disclaimer.html`) and every "
        "report email. Morning Coffee reads it at send time too. Line breaks are collapsed — "
        "it prints as one paragraph."
    )
    current = get_text()
    drifted = partial_text() != current
    if st.session_state.pop("compliance_saved", False):
        st.success("Saved — the partial and all future reports/emails now carry it.")

    # Edit lock: the box opens read-only every visit; 🔓 Unlock arms editing, and Save /
    # Cancel / Revert all re-lock it — so the legal text can never be changed by a stray
    # click or keystroke.
    locked = not st.session_state.get("compliance_unlocked", False)
    if locked and "compliance_disclaimer" in st.session_state:
        # Re-locking discards any un-saved edit left in the widget from the last unlock.
        st.session_state["compliance_disclaimer"] = current
    edited = st.text_area("Disclaimer text", value=current, height=320, disabled=locked,
                          key="compliance_disclaimer", label_visibility="collapsed")

    if locked:
        c_lock, c_status = st.columns([0.20, 0.80], vertical_alignment="center")
        with c_lock:
            if st.button("🔒 Unlock to edit", use_container_width=True):
                st.session_state["compliance_unlocked"] = True
                st.rerun()
    else:
        c_save, c_cancel, c_revert, c_status = st.columns(
            [0.14, 0.14, 0.24, 0.48], vertical_alignment="center")
        with c_save:
            if st.button("Save", type="primary", use_container_width=True,
                         disabled=(_normalise(edited) == current and not drifted)):
                try:
                    save_text(edited)
                    st.session_state["compliance_unlocked"] = False
                    st.session_state["compliance_saved"] = True
                    st.rerun()
                except ValueError as e:
                    st.error(str(e))
        with c_cancel:
            if st.button("🔓 Cancel", use_container_width=True,
                         help="Discard the edit and lock the box again"):
                st.session_state["compliance_unlocked"] = False
                st.rerun()
        with c_revert:
            if st.button("Revert to standard XP text", use_container_width=True,
                         disabled=not is_custom()):
                save_text(DEFAULT_TEXT)
                st.session_state["compliance_unlocked"] = False
                st.rerun()
    with c_status:
        st.caption(("**Custom** text in force (differs from the standard XP disclaimer)."
                    if is_custom() else "Standard XP Investments disclaimer in force.")
                   + ("" if not locked else "  ·  🔒 locked — unlock to edit"))

    # Drift guard: the partial is generated, but flag it if it ever disagrees (hand edit,
    # partial checkout, failed write) so a stale footer never goes unnoticed.
    if drifted:
        st.warning(
            "The report partial (`templates/_disclaimer.html`) does not match the stored "
            "text — unlock and press **Save** (or Revert) to regenerate it."
        )
